---
- name: Create Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'path_for_import_cert') }}"
    state: directory
    mode: "0755"
  register: idrac_certificate_created_directory
  check_mode: false
  delegate_to: "{{ lookup('env', 'idrac_certificate_delegate_to') }}"

- name: Setting up certificate path
  ansible.builtin.stat:
    path: "{{ lookup('env', 'path_for_import_cert') }}"
  register: idrac_certificate_check_file_created
  check_mode: false
  delegate_to: "{{ lookup('env', 'idrac_certificate_delegate_to') }}"

- name: Copy file from HTTPS share to local machine
  when: idrac_cert_name is defined and (idrac_cert_name | length > 0)
         and idrac_certificate_check_file_created.stat.exists
  ansible.builtin.uri:
    url: "https://{{ lookup('env', 'https_share_ip') }}{{  lookup('env', 'https_certificate_path') }}{{ item }}"
    dest: "{{ lookup('env', 'path_for_import_cert') }}"
    force_basic_auth: true
    validate_certs: false
    url_username: "{{ lookup('env', 'https_share_username') }}"
    url_password: "{{ lookup('env', 'https_share_password') }}"
  check_mode: false
  loop: "{{ idrac_cert_name }}"
  delegate_to: "{{ lookup('env', 'idrac_certificate_delegate_to') }}"
