---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    custom_certificate_failure: {}
    ca_cert_path: "{{ lookup('env', 'ca_cert_path') }}"
    custom_certificate_name: "{{ lookup('env', 'custom_certificate_name') }}"
    custom_certificate_name_pass: "{{ lookup('env', 'custom_certificate_name_pass') }}"
    base_path_for_import_certificate: "{{ lookup('env', 'base_path_for_import_certificate') }}"

  tasks:
    - name: Fetching firmware version for IDRAC
      ansible.builtin.include_tasks:
        file: ../__extract_firmware_version.yml
      vars:
        idrac_ip: "{{ lookup('env', 'hostname') }}"
        idrac_user: "{{ lookup('env', 'username') }}"
        idrac_password: "{{ lookup('env', 'password') }}"

    - name: Set expected firmware version
      ansible.builtin.set_fact:
        firmware_version_expected: "6.10.80.00"
        firmware_version_expected_export: "7.00.00.00"

    - name: Import CUSTOMCERTIFICATE without passphrase
      when: firmware_version is defined and "firmware_version >= firmware_version_expected" and custom_certificate_name
      block:
        - name: Import a custom certificate certificate
          ansible.builtin.import_role:
            name: dellemc.openmanage.idrac_certificate
          vars:
            hostname: "{{ lookup('env', 'hostname') }}"
            username: "{{ lookup('env', 'username') }}"
            password: "{{ lookup('env', 'password') }}"
            validate_certs: false
            ca_path: "{{ ca_cert_path }}"
            command: "import"
            certificate_type: "CUSTOMCERTIFICATE"
            certificate_path: "../files/{{ custom_certificate_name }}"
            idrac_certificate_delegate: "{{ lookup('env', 'idrac_certificate_delegate') }}"
            passphrase: ""

        - name: Waiting for idrac readiness
          ansible.builtin.wait_for:
            timeout: 60
          when:
            - not ansible_check_mode
            - idrac_certificate_out is defined
            - idrac_certificate_out.changed

        - name: Asserting operation with check mode.
          ansible.builtin.assert:
            that: idrac_certificate_out.msg == "Changes found to be applied."
          when: ansible_check_mode

        - name: Asserting operation with Normal/Idempotence mode.
          ansible.builtin.assert:
            that: idrac_certificate_out.msg == "Successfully performed the 'import' certificate operation.iDRAC has been reset successfully."
          when: not ansible_check_mode and idrac_certificate_out.changed

      rescue:
        - name: Set the failure messages for CUSTOMECERT
          ansible.builtin.set_fact:
            custom_certificate_failure: "{{  custom_certificate_failure | combine({'CUSTOMCERTIFICATE_WITHOUT_PASS_IMPORT': {'msg': ansible_failed_result.msg,
                      'failed_task_name': ansible_failed_task.name}}) }}"

    - name: Export CUSTOMCERTIFICATE
      when: firmware_version is defined and "firmware_version >= firmware_version_expected_export"
      block:
        - name: Export a custom certificate
          ansible.builtin.import_role:
            name: dellemc.openmanage.idrac_certificate
          vars:
            hostname: "{{ lookup('env', 'hostname') }}"
            username: "{{ lookup('env', 'username') }}"
            password: "{{ lookup('env', 'password') }}"
            validate_certs: false
            ca_path: "{{ ca_cert_path }}"
            command: "export"
            certificate_type: "CUSTOMCERTIFICATE"
            certificate_path: "../../files/"
            idrac_certificate_delegate: "{{ lookup('env', 'idrac_certificate_delegate') }}"
          when: not ansible_check_mode

        - name: Asserting operation with Normal/Idempotence mode.
          ansible.builtin.assert:
            that: idrac_certificate_out.msg == "Successfully performed the 'export' certificate operation."
          when: not ansible_check_mode and not idrac_certificate_out.changed

      rescue:
        - name: Set the failure messages for CUSTOMECERT
          ansible.builtin.set_fact:
            custom_certificate_failure: "{{  custom_certificate_failure | combine({'CUSTOMCERTIFICATE_EXPORT': {'msg': ansible_failed_result.msg,
                      'failed_task_name': ansible_failed_task.name}}) }}"

    - name: Import CUSTOMCERTIFICATE with passphrase
      when: firmware_version is defined and "firmware_version >= firmware_version_expected" and custom_certificate_name_pass
      block:

        - name: Import a custom certificate certificate with passphrase
          ansible.builtin.import_role:
            name: dellemc.openmanage.idrac_certificate
          vars:
            hostname: "{{ lookup('env', 'hostname') }}"
            username: "{{ lookup('env', 'username') }}"
            password: "{{ lookup('env', 'password') }}"
            validate_certs: false
            ca_path: "{{ ca_cert_path }}"
            command: "import"
            certificate_type: "CUSTOMCERTIFICATE"
            certificate_path: "../../files/{{ custom_certificate_name_pass }}"
            passphrase: "{{ lookup('env', 'passphrase') }}"
            idrac_certificate_delegate: "{{ lookup('env', 'idrac_certificate_delegate') }}"

        - name: Asserting operation with check mode.
          ansible.builtin.assert:
            that: idrac_certificate_out.msg == "Changes found to be applied."
          when: ansible_check_mode

        - name: Waiting for idrac readiness
          ansible.builtin.wait_for:
            timeout: 60
          when:
            - not ansible_check_mode
            - idrac_certificate_out is defined
            - idrac_certificate_out.changed

        - name: Asserting operation with Normal/Idempotence mode.
          ansible.builtin.assert:
            that: idrac_certificate_out.msg == "Successfully performed the 'import' certificate operation.iDRAC has been reset successfully."
          when: not ansible_check_mode and idrac_certificate_out.changed

      rescue:
        - name: Set the failure messages for CUSTOMECERT
          ansible.builtin.set_fact:
            custom_certificate_failure: "{{  custom_certificate_failure | combine({'CUSTOMCERTIFICATE_WITH_PASS_IMPORT': {'msg': ansible_failed_result.msg,
                      'failed_task_name': ansible_failed_task.name}}) }}"

    - name: Collecting failure
      ansible.builtin.debug:
        var: custom_certificate_failure
      when: custom_certificate_failure
      failed_when: true
